#!/bin/bash
chmod a-w Libraries/Language/Object.quorum
chmod a-w Libraries/Language/Errors/*
chmod a-w Libraries/Language/Support/*
chmod a-w Libraries/Language/Types/*
chmod a-w Libraries/Compute/*
chmod a-w Libraries/Sound/*
chmod a-w Libraries/System/*
chmod a-w Libraries/Containers/*
chmod a-w Libraries/Containers/Blueprints/*
chmod a-w Libraries/Containers/Support/*