/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AccessibleHandlers_WindowsAccessibleHandler */

#ifndef _Included_AccessibleHandlers_WindowsAccessibleHandler
#define _Included_AccessibleHandlers_WindowsAccessibleHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AccessibleHandlers_WindowsAccessibleHandler
 * Method:    Initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AccessibleHandlers_WindowsAccessibleHandler_Initialize
  (JNIEnv *, jobject);

/*
 * Class:     AccessibleHandlers_WindowsAccessibleHandler
 * Method:    Terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AccessibleHandlers_WindowsAccessibleHandler_Terminate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
