/* DO NOT EDIT THIS FILE - it is machine generated */
#include  <JavaVM/jni.h>
/* Header for class AccessibleHandlers_MacAccessibleHandler */

#ifndef _Included_AccessibleHandlers_MacAccessibleHandler
#define _Included_AccessibleHandlers_MacAccessibleHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AccessibleHandlers_MacAccessibleHandler
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AccessibleHandlers_MacAccessibleHandler_Initialize
  (JNIEnv *env, jobject jobj);

/*
 * Class:     AccessibleHandlers_MacAccessibleHandler
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AccessibleHandlers_MacAccessibleHandler_Terminate
  (JNIEnv *env, jobject jobj);

#ifdef __cplusplus
}
#endif
#endif
