/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.quorum.projects;

import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;
import javax.swing.JFileChooser;
import org.netbeans.api.project.Project;
import org.openide.filesystems.FileObject;
import org.openide.filesystems.FileUtil;

/**
 *
 * @author stefika
 */
public class MobilePanel extends javax.swing.JPanel {
    private Project project;
    /**
     * Creates new form MobilePanel
     */
    public MobilePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mobileFolderFileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        browseButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        provisioningTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        signingKeyTextField = new javax.swing.JTextField();
        resourcesTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        mobileFolderFileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(MobilePanel.class, "MobilePanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(browseButton, org.openide.util.NbBundle.getMessage(MobilePanel.class, "MobilePanel.browseButton.text")); // NOI18N
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(MobilePanel.class, "MobilePanel.jLabel2.text")); // NOI18N

        provisioningTextField.setText(org.openide.util.NbBundle.getMessage(MobilePanel.class, "MobilePanel.provisioningTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(MobilePanel.class, "MobilePanel.jLabel3.text")); // NOI18N

        signingKeyTextField.setText(org.openide.util.NbBundle.getMessage(MobilePanel.class, "MobilePanel.signingKeyTextField.text")); // NOI18N

        resourcesTextField.setText(org.openide.util.NbBundle.getMessage(MobilePanel.class, "MobilePanel.resourcesTextField.text")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(MobilePanel.class, "MobilePanel.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(MobilePanel.class, "MobilePanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addComponent(provisioningTextField)
            .addComponent(signingKeyTextField)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resourcesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resourcesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(provisioningTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signingKeyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        File defaultFolder = FileUtil.toFile(project.getProjectDirectory());
        mobileFolderFileChooser.setCurrentDirectory(defaultFolder);
        int show = mobileFolderFileChooser.showDialog(this, "choose");
        if(show == JFileChooser.APPROVE_OPTION) {
            File file = mobileFolderFileChooser.getSelectedFile();
            String path = getPathRelativeToProject(file);
            resourcesTextField.setText(path);
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        resourcesTextField.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    public String getPathRelativeToProject(File file) {
        String absolutePath = file.getAbsolutePath();
        QuorumProject proj = (QuorumProject) project;
        FileObject directory = proj.getProjectDirectory();
        String projectPath = FileUtil.toFile(directory).getAbsolutePath();
        Path sourceFile = Paths.get(projectPath);
        Path targetFile = Paths.get(absolutePath); 
        Path relativePath = sourceFile.relativize(targetFile);

        return relativePath.toString();
    }
    
    public Project getProject() {
        return project;
    }
    
    public void setProject(Project project) {
        this.project = project;
        loadProperties();
    }
    
    public String getiPhoneProvisioning() {
        return provisioningTextField.getText();
    }
    
    public String getiPhoneSigningKey() {
        return signingKeyTextField.getText();
    }
    
    public String getMobileAssetsFolder() {
        return resourcesTextField.getText();
    }
    
    private void loadProperties() {
        Properties properties = project.getLookup().lookup(Properties.class);
        String assets = properties.getProperty(QuorumProject.QUORUM_MOBILE_ASSETS_FOLDER);
        String provision = properties.getProperty(QuorumProject.QUORUM_IPHONE_PROVISION);
        String signingKey = properties.getProperty(QuorumProject.QUORUM_IPHONE_SIGNING_KEY);
        
        if(assets != null) {
            resourcesTextField.setText(assets);
        } else {
            resourcesTextField.setText("media");
        }
        
        if(provision != null) {
            provisioningTextField.setText(provision);
        }
        
        if(signingKey != null) {
            signingKeyTextField.setText(signingKey);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JFileChooser mobileFolderFileChooser;
    private javax.swing.JTextField provisioningTextField;
    private javax.swing.JTextField resourcesTextField;
    private javax.swing.JTextField signingKeyTextField;
    // End of variables declaration//GEN-END:variables
}
