/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.quorum.projects;

import java.io.File;
import java.util.Properties;
import javax.swing.JFileChooser;
import org.netbeans.api.project.Project;

/**
 *
 * @author astefik
 */
public class ProjectInformationPanel extends javax.swing.JPanel {

    private Project project;
    /**
     * Creates new form ProjectInformationPanel
     */
    public ProjectInformationPanel() {
        initComponents();
    }
    
    private void loadProperties() {
        Properties properties = project.getLookup().lookup(Properties.class);
        String property = properties.getProperty(QuorumProject.QUORUM_PROJECT_TYPE);
        if(property == null || property.compareTo(QuorumProject.QUORUM_CONSOLE_PROJECT) == 0) {
            projectRadioButton.setSelected(true);
        } else if(property.compareTo(QuorumProject.QUORUM_COMPILED_WEB_PROJECT) == 0) {
            compiledWebProjectRadioButton.setSelected(true);
        }
    }
    
    public Project getProject() {
        return project;
    }
    
    public void setProject(Project project) {
        this.project = project;
        loadProperties();
    }
    
    public String getQuorumProjectType() {
        if(projectRadioButton.isSelected()) {
            return QuorumProject.QUORUM_CONSOLE_PROJECT;
        } else {
            return QuorumProject.QUORUM_COMPILED_WEB_PROJECT;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectTypeButtonGroup = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        projectRadioButton = new javax.swing.JRadioButton();
        compiledWebProjectRadioButton = new javax.swing.JRadioButton();

        jRadioButton1.setText("jRadioButton1");

        jLabel2.setText("Select the type of Quorum project you would like");

        projectTypeButtonGroup.add(projectRadioButton);
        projectRadioButton.setText("Quorum Project");
        projectRadioButton.setToolTipText("Select this radio button if you would like to have a normal Quorum project");

        projectTypeButtonGroup.add(compiledWebProjectRadioButton);
        compiledWebProjectRadioButton.setText("Quorum Web Project");
        compiledWebProjectRadioButton.setToolTipText("Use this option if you want to compile your Quorum code for use in a Java Web Server, like Tomcat or Glassfish");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectRadioButton)
                    .addComponent(compiledWebProjectRadioButton))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compiledWebProjectRadioButton)
                .addGap(0, 226, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton compiledWebProjectRadioButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton projectRadioButton;
    private javax.swing.ButtonGroup projectTypeButtonGroup;
    // End of variables declaration//GEN-END:variables
}
