/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class plugins_quorum_Libraries_Game_Graphics_IOSGraphics */

#ifndef _Included_plugins_quorum_Libraries_Game_Graphics_IOSGraphics
#define _Included_plugins_quorum_Libraries_Game_Graphics_IOSGraphics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_init
  (JNIEnv *, jclass);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glActiveTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glActiveTexture
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glAttachShader
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glAttachShader
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glBindAttribLocation
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glBindAttribLocation
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glBindBuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glBindBuffer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glBindFramebuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glBindFramebuffer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glBindRenderbuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glBindRenderbuffer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glBindTexture
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glBindTexture
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glBlendColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glBlendColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glBlendEquation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glBlendEquation
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glBlendEquationSeparate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glBlendEquationSeparate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glBlendFunc
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glBlendFunc
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glBlendFuncSeparate
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glBlendFuncSeparate
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glBufferData
 * Signature: (IILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glBufferData
  (JNIEnv *, jobject, jint, jint, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glBufferSubData
 * Signature: (IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glBufferSubData
  (JNIEnv *, jobject, jint, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glCheckFramebufferStatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glCheckFramebufferStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glClear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glClear
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glClearColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glClearColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glClearDepthf
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glClearDepthf
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glClearStencil
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glClearStencil
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glColorMask
 * Signature: (ZZZZ)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glColorMask
  (JNIEnv *, jobject, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glCompileShader
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glCompileShader
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glCompressedTexImage2D
 * Signature: (IIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glCompressedTexImage2D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glCompressedTexSubImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glCompressedTexSubImage2D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glCopyTexImage2D
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glCopyTexImage2D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glCopyTexSubImage2D
 * Signature: (IIIIIIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glCopyTexSubImage2D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glCreateProgram
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glCreateProgram
  (JNIEnv *, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glCreateShader
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glCreateShader
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glCullFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glCullFace
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glDeleteBuffers
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glDeleteBuffers
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glDeleteBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glDeleteBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glDeleteFramebuffers
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glDeleteFramebuffers
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glDeleteFramebuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glDeleteFramebuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glDeleteProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glDeleteProgram
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glDeleteRenderbuffers
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glDeleteRenderbuffers
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glDeleteRenderbuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glDeleteRenderbuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glDeleteShader
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glDeleteShader
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glDeleteTextures
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glDeleteTextures
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glDeleteTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glDeleteTexture
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glDepthFunc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glDepthFunc
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glDepthMask
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glDepthMask
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glDepthRangef
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glDepthRangef
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glDetachShader
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glDetachShader
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glDisable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glDisable
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glDisableVertexAttribArray
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glDisableVertexAttribArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glDrawArrays
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glDrawArrays
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glDrawElements
 * Signature: (IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glDrawElements__IIILjava_nio_Buffer_2
  (JNIEnv *, jobject, jint, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glDrawElements
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glDrawElements__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glEnable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glEnable
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glEnableVertexAttribArray
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glEnableVertexAttribArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glFinish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glFinish
  (JNIEnv *, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glFlush
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glFlush
  (JNIEnv *, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glFramebufferRenderbuffer
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glFramebufferRenderbuffer
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glFramebufferTexture2D
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glFramebufferTexture2D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glFrontFace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glFrontFace
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGenBuffers
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGenBuffers
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGenBuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGenBuffer
  (JNIEnv *, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGenerateMipmap
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGenerateMipmap
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGenFramebuffers
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGenFramebuffers
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGenFramebuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGenFramebuffer
  (JNIEnv *, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGenRenderbuffers
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGenRenderbuffers
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGenRenderbuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGenRenderbuffer
  (JNIEnv *, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGenTextures
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGenTextures
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGenTexture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGenTexture
  (JNIEnv *, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetActiveAttrib
 * Signature: (IILjava/nio/IntBuffer;Ljava/nio/Buffer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetActiveAttrib
  (JNIEnv *, jobject, jint, jint, jobject, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetActiveUniform
 * Signature: (IILjava/nio/IntBuffer;Ljava/nio/Buffer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetActiveUniform
  (JNIEnv *, jobject, jint, jint, jobject, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetAttachedShaders
 * Signature: (IILjava/nio/Buffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetAttachedShaders
  (JNIEnv *, jobject, jint, jint, jobject, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetAttribLocation
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetAttribLocation
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetBooleanv
 * Signature: (ILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetBooleanv
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetBufferParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetBufferParameteriv
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetError
  (JNIEnv *, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetFloatv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetFloatv
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetFramebufferAttachmentParameteriv
 * Signature: (IIILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetFramebufferAttachmentParameteriv
  (JNIEnv *, jobject, jint, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetIntegerv
 * Signature: (ILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetIntegerv
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetProgramiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetProgramiv
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetProgramInfoLog
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetProgramInfoLog
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetRenderbufferParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetRenderbufferParameteriv
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetShaderiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetShaderiv
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetShaderInfoLog
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetShaderInfoLog
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetShaderPrecisionFormat
 * Signature: (IILjava/nio/IntBuffer;Ljava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetShaderPrecisionFormat
  (JNIEnv *, jobject, jint, jint, jobject, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetShaderSource
 * Signature: (IILjava/nio/Buffer;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetShaderSource
  (JNIEnv *, jobject, jint, jint, jobject, jstring);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetString
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetTexParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetTexParameterfv
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetTexParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetTexParameteriv
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetUniformfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetUniformfv
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetUniformiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetUniformiv
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetUniformLocation
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetUniformLocation
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetVertexAttribfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetVertexAttribfv
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetVertexAttribiv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetVertexAttribiv
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glGetVertexAttribPointerv
 * Signature: (IILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glGetVertexAttribPointerv
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glHint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glHint
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glIsBuffer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glIsBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glIsEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glIsEnabled
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glIsFramebuffer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glIsFramebuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glIsProgram
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glIsProgram
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glIsRenderbuffer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glIsRenderbuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glIsShader
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glIsShader
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glIsTexture
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glIsTexture
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glLineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glLineWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glLinkProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glLinkProgram
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glPixelStorei
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glPixelStorei
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glPolygonOffset
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glPolygonOffset
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glReadPixels
 * Signature: (IIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glReadPixels
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glReleaseShaderCompiler
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glReleaseShaderCompiler
  (JNIEnv *, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glRenderbufferStorage
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glRenderbufferStorage
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glSampleCoverage
 * Signature: (FZ)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glSampleCoverage
  (JNIEnv *, jobject, jfloat, jboolean);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glScissor
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glScissor
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glShaderBinary
 * Signature: (ILjava/nio/IntBuffer;ILjava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glShaderBinary
  (JNIEnv *, jobject, jint, jobject, jint, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glShaderSource
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glShaderSource
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glStencilFunc
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glStencilFunc
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glStencilFuncSeparate
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glStencilFuncSeparate
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glStencilMask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glStencilMask
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glStencilMaskSeparate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glStencilMaskSeparate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glStencilOp
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glStencilOp
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glStencilOpSeparate
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glStencilOpSeparate
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glTexImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glTexImage2D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glTexParameterf
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glTexParameterf
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glTexParameterfv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glTexParameterfv
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glTexParameteri
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glTexParameteri
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glTexParameteriv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glTexParameteriv
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glTexSubImage2D
 * Signature: (IIIIIIIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glTexSubImage2D
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform1f
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform1f
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform1fv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform1fv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform1fv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform1fv__II_3FI
  (JNIEnv *, jobject, jint, jint, jfloatArray, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform1i
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform1i
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform1iv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform1iv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform1iv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform1iv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform2f
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform2f
  (JNIEnv *, jobject, jint, jfloat, jfloat);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform2fv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform2fv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform2fv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform2fv__II_3FI
  (JNIEnv *, jobject, jint, jint, jfloatArray, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform2i
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform2i
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform2iv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform2iv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform2iv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform2iv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform3f
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform3f
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform3fv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform3fv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform3fv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform3fv__II_3FI
  (JNIEnv *, jobject, jint, jint, jfloatArray, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform3i
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform3i
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform3iv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform3iv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform3iv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform3iv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform4f
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform4f
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform4fv
 * Signature: (IILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform4fv__IILjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform4fv
 * Signature: (II[FI)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform4fv__II_3FI
  (JNIEnv *, jobject, jint, jint, jfloatArray, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform4i
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform4i
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform4iv
 * Signature: (IILjava/nio/IntBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform4iv__IILjava_nio_IntBuffer_2
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniform4iv
 * Signature: (II[II)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniform4iv__II_3II
  (JNIEnv *, jobject, jint, jint, jintArray, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniformMatrix2fv
 * Signature: (IIZLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniformMatrix2fv__IIZLjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jint, jboolean, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniformMatrix2fv
 * Signature: (IIZ[FI)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniformMatrix2fv__IIZ_3FI
  (JNIEnv *, jobject, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniformMatrix3fv
 * Signature: (IIZLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniformMatrix3fv__IIZLjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jint, jboolean, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniformMatrix3fv
 * Signature: (IIZ[FI)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniformMatrix3fv__IIZ_3FI
  (JNIEnv *, jobject, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniformMatrix4fv
 * Signature: (IIZLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniformMatrix4fv__IIZLjava_nio_FloatBuffer_2
  (JNIEnv *, jobject, jint, jint, jboolean, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUniformMatrix4fv
 * Signature: (IIZ[FI)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUniformMatrix4fv__IIZ_3FI
  (JNIEnv *, jobject, jint, jint, jboolean, jfloatArray, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glUseProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glUseProgram
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glValidateProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glValidateProgram
  (JNIEnv *, jobject, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glVertexAttrib1f
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glVertexAttrib1f
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glVertexAttrib1fv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glVertexAttrib1fv
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glVertexAttrib2f
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glVertexAttrib2f
  (JNIEnv *, jobject, jint, jfloat, jfloat);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glVertexAttrib2fv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glVertexAttrib2fv
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glVertexAttrib3f
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glVertexAttrib3f
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glVertexAttrib3fv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glVertexAttrib3fv
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glVertexAttrib4f
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glVertexAttrib4f
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glVertexAttrib4fv
 * Signature: (ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glVertexAttrib4fv
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glVertexAttribPointer
 * Signature: (IIIZILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glVertexAttribPointer__IIIZILjava_nio_Buffer_2
  (JNIEnv *, jobject, jint, jint, jint, jboolean, jint, jobject);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glVertexAttribPointer
 * Signature: (IIIZII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glVertexAttribPointer__IIIZII
  (JNIEnv *, jobject, jint, jint, jint, jboolean, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_IOSGraphics
 * Method:    glViewportJni
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_IOSGraphics_glViewportJni
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif