/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class plugins_quorum_Libraries_Game_Graphics_PixelMap */

#ifndef _Included_plugins_quorum_Libraries_Game_Graphics_PixelMap
#define _Included_plugins_quorum_Libraries_Game_Graphics_PixelMap
#ifdef __cplusplus
extern "C" {
#endif
#undef plugins_quorum_Libraries_Game_Graphics_PixelMap_FORMAT_ALPHA
#define plugins_quorum_Libraries_Game_Graphics_PixelMap_FORMAT_ALPHA 1L
#undef plugins_quorum_Libraries_Game_Graphics_PixelMap_FORMAT_LUMINANCE_ALPHA
#define plugins_quorum_Libraries_Game_Graphics_PixelMap_FORMAT_LUMINANCE_ALPHA 2L
#undef plugins_quorum_Libraries_Game_Graphics_PixelMap_FORMAT_RGB888
#define plugins_quorum_Libraries_Game_Graphics_PixelMap_FORMAT_RGB888 3L
#undef plugins_quorum_Libraries_Game_Graphics_PixelMap_FORMAT_RGBA8888
#define plugins_quorum_Libraries_Game_Graphics_PixelMap_FORMAT_RGBA8888 4L
#undef plugins_quorum_Libraries_Game_Graphics_PixelMap_FORMAT_RGB565
#define plugins_quorum_Libraries_Game_Graphics_PixelMap_FORMAT_RGB565 5L
#undef plugins_quorum_Libraries_Game_Graphics_PixelMap_FORMAT_RGBA4444
#define plugins_quorum_Libraries_Game_Graphics_PixelMap_FORMAT_RGBA4444 6L
#undef plugins_quorum_Libraries_Game_Graphics_PixelMap_SCALE_NEAREST
#define plugins_quorum_Libraries_Game_Graphics_PixelMap_SCALE_NEAREST 0L
#undef plugins_quorum_Libraries_Game_Graphics_PixelMap_SCALE_LINEAR
#define plugins_quorum_Libraries_Game_Graphics_PixelMap_SCALE_LINEAR 1L
#undef plugins_quorum_Libraries_Game_Graphics_PixelMap_BLEND_NONE
#define plugins_quorum_Libraries_Game_Graphics_PixelMap_BLEND_NONE 0L
#undef plugins_quorum_Libraries_Game_Graphics_PixelMap_BLEND_SOURCE_OVER
#define plugins_quorum_Libraries_Game_Graphics_PixelMap_BLEND_SOURCE_OVER 1L
/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_PixelMap
 * Method:    Load
 * Signature: ([J[BII)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_plugins_quorum_Libraries_Game_Graphics_PixelMap_Load
  (JNIEnv *, jclass, jlongArray, jbyteArray, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_PixelMap
 * Method:    newPixmap
 * Signature: ([JIII)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_plugins_quorum_Libraries_Game_Graphics_PixelMap_NewPixelMap
  (JNIEnv *, jclass, jlongArray, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_PixelMap
 * Method:    Free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_PixelMap_Free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_PixelMap
 * Method:    Clear
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_PixelMap_Clear
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_PixelMap
 * Method:    SetPixel
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_PixelMap_SetPixel
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_PixelMap
 * Method:    GetPixel
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_plugins_quorum_Libraries_Game_Graphics_PixelMap_GetPixel
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_PixelMap
 * Method:    DrawLine
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_PixelMap_DrawLine
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_PixelMap
 * Method:    DrawRectangle
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_PixelMap_DrawRectangle
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_PixelMap
 * Method:    DrawCircle
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_PixelMap_DrawCircle
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_PixelMap
 * Method:    FillRectangle
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_PixelMap_FillRectangle
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_PixelMap
 * Method:    FillCircle
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_PixelMap_FillCircle
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_PixelMap
 * Method:    FillTriangle
 * Signature: (JIIIIIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_PixelMap_FillTriangle
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_PixelMap
 * Method:    DrawPixmap
 * Signature: (JJIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_PixelMap_DrawPixelMap
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_PixelMap
 * Method:    SetBlendNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_PixelMap_SetBlendNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_PixelMap
 * Method:    SetScale
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_PixelMap_SetScale
  (JNIEnv *, jclass, jint);

/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_PixelMap
 * Method:    GetFailureReason
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_plugins_quorum_Libraries_Game_Graphics_PixelMap_GetFailureReason
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
