/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package plugins.quorum.Libraries.System;

/**
 * This class allows for loading and unloading of any system related resources
 * in Quorum generated bytecode.
 * 
 * @author Andreas Stefik
 */
public class Quorum {
    /**
     * This flag is used to determine the behavior of input() statements. When
     * running unit tests, it is unfavorable to load AWT, as certain types of
     * test cases (such as uncaught exceptions) never terminate properly.
     * 
     * If the VM is invoked with the command line argument -DQuorumUnitTest,
     * AWT will not be loaded.
     */
    public static final String QUORUM_TEST_JVM_FLAG = "QuorumUnitTest";
    
    public static void Load() {
        Console.Load();
        
        // Should we register an uncaught exceptions handler? This handler will
        // force Quorum to return a system exit value of "2" when an uncaught
        // Quorum exception occurs. Non-quorum exceptions will still return "1".
        if (System.getProperty(QUORUM_TEST_JVM_FLAG) != null) {
            Thread.setDefaultUncaughtExceptionHandler(new ExceptionHandler());
        }
    }
    
    public static void Unload() {
        Console.Unload();
        
        System.exit(0);
    }
}
