/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package plugins.quorum.Libraries.System;

/**
 * This class allows for loading and unloading of any system related resources
 * in Quorum generated bytecode.
 * 
 * @author Andreas Stefik
 */
public class Quorum {
    public static void Load() {
        Console.Load();
    }
    
    public static void Unload() {
        Console.Unload();
    }
}
